export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const POST_LOADING = 'POST_LOADING'
export const ADD_POST = 'ADD_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const UPDATE_POST_ON_PAGE = 'UPDATE_POST_ON_PAGE'
export const UPDATE_POSTS = 'UPDATE_POSTS'
export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'
export const DELETE_POST = 'DELETE_POST'
export const CLEAR_POSTS = 'CLEAR_POSTS'

export const SUBSCRIPTION_LOADING = 'SUBSCRIPTION_LOADING'
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION'
export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS'
export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION'

export const USER_LOADING = 'USER_LOADING'
export const GET_USER = 'GET_USER'

//
export type SET_CURRENT_USER = typeof SET_CURRENT_USER

export type POST_LOADING = typeof POST_LOADING
export type ADD_POST = typeof ADD_POST
export type UPDATE_POST = typeof UPDATE_POST
export type UPDATE_POST_ON_PAGE = typeof UPDATE_POST_ON_PAGE
export type UPDATE_POSTS = typeof UPDATE_POSTS
export type GET_POSTS = typeof GET_POSTS
export type GET_POST = typeof GET_POST
export type DELETE_POST = typeof DELETE_POST
export type CLEAR_POSTS = typeof CLEAR_POSTS

export type SUBSCRIPTION_LOADING = typeof SUBSCRIPTION_LOADING
export type ADD_SUBSCRIPTION = typeof ADD_SUBSCRIPTION
export type GET_SUBSCRIPTIONS = typeof GET_SUBSCRIPTIONS
export type DELETE_SUBSCRIPTION = typeof DELETE_SUBSCRIPTION

export type USER_LOADING = typeof USER_LOADING
export type GET_USER = typeof GET_USER
 